apiVersion: v1
kind: Service
metadata:
  name: e2e-lane-nextjs
  namespace: colossus-e2e-lane-nextjs
  labels:
    app: e2e-lane-nextjs
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: e2e-lane-nextjs
  ports:
    - port: 80
      targetPort: 80
